// Session
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_ERROR = 'LOGIN_FACEBOOK_ERROR';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const REGISTER_PROFILE = 'REGISTER_PROFILE';
export const REGISTER_PROFILE_SUCCESS = 'REGISTER_PROFILE_SUCCESS';
export const REGISTER_PROFILE_ERROR = 'REGISTER_PROFILE_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';

export const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_ERROR = 'UPLOAD_PROFILE_IMAGE_ERROR';


//Room
export const REGISTER_ROOM = 'REGISTER_ROOM';
export const REGISTER_ROOM_SUCCESS = 'REGISTER_ROOM_SUCCESS';
export const REGISTER_ROOM_ERROR = 'REGISTER_ROOM_ERROR';

export const GET_ROOM = 'GET_ROOM';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_ERROR = 'GET_ROOM_ERROR';

export const GET_USER_ROOMS = 'GET_USER_ROOMS';
export const GET_USER_ROOMS_SUCCESS = 'GET_USER_ROOMS_SUCCESS';
export const GET_USER_ROOMS_ERROR = 'GET_USER_ROOMS_ERROR';

export const SEARCH_ROOMS_BY_LOCATION = 'SEARCH_ROOMS_BY_LOCATION';
export const SEARCH_ROOMS_BY_LOCATION_SUCCESS = 'SEARCH_ROOMS_BY_LOCATION_SUCCESS';
export const SEARCH_ROOMS_BY_LOCATION_ERROR = 'SEARCH_ROOMS_BY_LOCATION_ERROR';

export const GET_FAVOURITE_ROOM = 'GET_FAVOURITE_ROOM_';
export const GET_FAVOURITE_ROOM_SUCCESS = 'GET_FAVOURITE_ROOM_SUCCESS';
export const GET_FAVOURITE_ROOM_ERROR = 'GET_FAVOURITE_ROOM_ERROR';


//Suggestion 
export const GET_PROFILE_SUGGESTION = 'GET_PROFILE_SUGGESTION';
export const GET_PROFILE_SUGGESTION_SUCCESS = 'GET_PROFILE_SUGGESTION_SUCCESS';
export const GET_PROFILE_SUGGESTION_ERROR = 'GET_PROFILE_SUGGESTION_ERROR';